export const ApiConfig = {
  domain_name: 'https://tamkeen-dev.com',
  BASE_URL: 'https://tamkeen-dev.com/api',
    ENDPOINTS: {
        REGISTRATION: '/user/registerpass',
        LOGIN: '/user/login',
        LOGOUT: '/user/logout',
        DEDLETE_USER: '/user',
        PROFILE: '/user',
        USER_LIST: '/users-list',
        EDIT_USER: '/user/34',
        USER_PICTURE: '/file/upload/user/user/user_picture',
        CREATE_BLOG: '/node',
        BLOG_LIST: '/blogs-api',
        ARTICLES_LIST: '/blogs-api-current-user',
        ARTICLES_DITAILS: '/node',
        ARTICLES_UPDAIT: '/node',
        DELETE_ARTICLES: '/node',
        IMAGE_FIELD: '/file/upload/node/blog/field_image',
        GALLERY_FIELD: '/file/upload/node/blog/field_gallery',
        TAGS: '/terms/tags',
        CATEGORY: '/terms/category',
        FAQ_CATEGORY: '/terms/faq-category',
        FIND: '/terms/hear',
        TESTIOMONIALS: '/testimonials',
        FAQ_LIST: '/faq-list',
        TOKEN: '/session/token',
    },
}

